"""empty message

Revision ID: 544db32d0712
Revises: 
Create Date: 2024-01-15 20:02:17.789626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544db32d0712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_w_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_tax_code', sa.String(length=255), nullable=True),
    sa.Column('w_tax_name', sa.String(length=255), nullable=True),
    sa.Column('w_tax_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('pass_word', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('staff', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('tin', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('account_title', sa.String(length=255), nullable=True),
    sa.Column('account_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_category_id'], ['account_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('ap_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('receiving_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_tax_name', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_w_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('w_tax_code', sa.String(length=255), nullable=True),
    sa.Column('w_tax_name', sa.String(length=255), nullable=True),
    sa.Column('w_tax_rate', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_tax_name', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payable_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payable_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('purchase_tax_id', sa.Integer(), nullable=False),
    sa.Column('purchase_w_tax_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['payable.id'], ),
    sa.ForeignKeyConstraint(['purchase_tax_id'], ['purchase_tax.id'], ),
    sa.ForeignKeyConstraint(['purchase_w_tax_id'], ['purchase_w_tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payable_detail')
    op.drop_table('sales_tax')
    op.drop_table('purchase_w_tax')
    op.drop_table('purchase_tax')
    op.drop_table('payable')
    op.drop_table('user_role')
    op.drop_table('account')
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('sales_w_tax')
    op.drop_table('role')
    op.drop_table('measure')
    op.drop_table('item')
    op.drop_table('account_category')
    # ### end Alembic commands ###
