"""empty message

Revision ID: 5704cef28be9
Revises: 498fb485a952
Create Date: 2023-12-29 10:11:37.756691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5704cef28be9'
down_revision = '498fb485a952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_tax_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_tax')
    # ### end Alembic commands ###
