"""empty message

Revision ID: 7d4e5ff7bafc
Revises: fc9dc78b21dd
Create Date: 2024-01-14 05:23:51.343543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4e5ff7bafc'
down_revision = 'fc9dc78b21dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sales_tax', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_tax', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('purchase_tax', schema=None) as batch_op:
        batch_op.drop_column('tax_rate')

    # ### end Alembic commands ###
