"""empty message

Revision ID: 9146c5a91855
Revises: 6e42bbe587da
Create Date: 2023-12-17 12:45:07.848134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9146c5a91855'
down_revision = '6e42bbe587da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=255), nullable=True),
    sa.Column('account_title', sa.String(length=255), nullable=True),
    sa.Column('account_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_category_id'], ['account_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('account_category')
    # ### end Alembic commands ###
