"""empty message

Revision ID: fc9dc78b21dd
Revises: d6ea22eb6eb0
Create Date: 2024-01-13 21:30:16.351239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9dc78b21dd'
down_revision = 'd6ea22eb6eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payable_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payable_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
